# Site settings
title: Mark Roxberry
header-img: img/home-bg.png
email: mark@roxberries.com
copyright_name: Mark Roxberry
description: "coder, maker, hacker, mentor"
baseurl: "/"
url: "https://roxberry.dev"
twitter_username: roxberry
github_username:  roxberry
facebook_username:  roxberry
email_username:  mark@roxberries.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "contact.html", "mail", "Gemfile", "Gemfile.lock", "README.md", "LICENSE"]

plugins: [jekyll-paginate, jekyll-feed]
