# Site settings
title: Mark Roxberry
catch-phrase: "Always Look on the Bright Side of Life"
header-img: img/home-bg.png
header-img-400: img/home-bg-400.png
header-img-post: img/home-bg-post.png
email: mark@roxberries.com
copyright_name: Mark Roxberry
description: "coder, maker, hacker, mentor"
baseurl: ""
url: "http://roxberry.dev"
twitter_username: roxberry
github_username:  roxberry
facebook_username:  roxberry
email_username:  contact@roxberry.dev
version: 1.10142018

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 6
include: ["_pages"]
exclude: ["about.md", "tag.md", "tasks.md", "futureengineers.md", "_spikes", "_drafts", "less","node_modules","Gruntfile.js","package.json","README.md", "contact.html", "mail", "Gemfile", "Gemfile.lock", "README.md", "LICENSE"]

# Server settings
webrick:
  headers:
    "Access-Control-Allow-Origin": "*"
   
plugins: [jekyll-paginate, jekyll-feed]