on:
  push:
    branches:
      - master

jobs:
  jekyll_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v1
        with:
          ref: master
          fetch-depth: 10

      # Note the following may not be required in future versions of Jekyll Build Actions
      - name: Create Destination
        run: mkdir -vp ~/www/roxberry

      - name: Build Jekyll
        uses: gha-utilities/jekyll-build@v0.0.2
        with:
          source: ./
          destination: ~/www/roxberry

      # - name: Checkout
      #   uses: actions/checkout@v1
      #   with:
      #     ref: deployment-test
      #     fetch-depth: 1
      #     submodules: true

      - name: Copy built site files into Git branch
        run: ls ~/www/roxberry && cp ~/www/roxberry -r ~/www/repository-name ./ && ls ./

      - name: Add and Commit changes to pr-pages branch
        run: |
          git config --local user.email 'roxberry@outlook.com'
          git config --local user.name 'Mark Roxberry'
          git add -A .
          git commit -m 'Updates compiled site files'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: deployment-test
