on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          path: ./source
          ref: master
          fetch-depth: 10

      # Note the following may not be required in future versions of Jekyll Build Actions
      - name: Create Destination
        run: mkdir -vp /home/runner/www/roxberry

      - name: Build Jekyll
        uses: gha-utilities/jekyll-build@v0.0.2
        with:
          source: ./source
          destination: ./_site

      - name: Check Build
        run: ls ./_site

      # - name: Checkout Destination
      #   uses: actions/checkout@v2
      #   with:
      #     path: ./dest
      #     ref: deployment-test
      #     fetch-depth: 1

      # - name: Copy to Git branch
      #   run: | 
      #     echo 'list before' && 
      #     ls /home/runner/www/roxberry && 
      #     cp -r /home/runner/www/roxberry ./dest && 
      #     echo 'list after' && 
      #     ls ./
      #     ls ./dest && 
      #     ls ./dest/roxberry &&
      #     echo 'build loc?' &&
      #     ls /home/runner/www/roxberry

      # - name: Add and Commit changes to pr-pages branch
      #   run: |
      #     git config --local user.email 'roxberry@outlook.com'
      #     git config --local user.name 'Mark Roxberry'
      #     git add -A .
      #     git commit -m 'Updates compiled site files'

      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: deployment-test
      #     force: true
