name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
       node-version: [ 12.x]
       ruby: [ '2.6.7' ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: gem install --user-install bundler jekyll
    - run: npm install
    - run: grunt deploy
      env:
        CI: true
