name: deploy

on:
  push:
    branches:
      - master

jobs:
  run-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: checkout
        uses: actions/checkout@master
      - name: dependencies
        uses: docker://jekyll/jekyll
        env:
          BUNDLE_PATH: .bundle
        with: 
          entrypoint: bundle
          args: install -j=4
