name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
       node-version: [8.x, 10.x, 12.x]
       ruby: [ '2.3.3', '2.6' ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: gem build
    - run: npm install
    - run: grunt deploy
      env:
        CI: true
