name: Roxberry.DEV Build

on:
  push:
    branches:
    - master

jobs: 
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build ROXBERRY.DEV to deployment branch.
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          REMOVE_GEMLOCK: true
          JEKYLL_ROOT: "./"
          REMOTE_BRANCH: "deployment"
        uses: roxberry/jekyll-build-optional-deploy-gh-pages@master
