name: deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - deployment
    paths:
      - 'dist/**'

jobs:
  run-deploy:
    runs-on: ubuntu-latest
    container: jekyll/jekyll:4.0.0
    steps:
      # Checkout
      - name: Checkout Code
        uses: actions/checkout@master
      # Jekyll  
      - name: Get Jekyll Dependencies
        run: |
          gem install bundler jekyll
          bundle install --jobs 4 --retry 3
      # Grunt
      - name: Get Grunt Dependencies
        run: |
          npm install
      # Build
      - name: Grunt Build and Copy
        run: 
        mkdir dist
        chmod ugo+rwx dist
        npm run build
        
        