name: deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - 'dist/**'

jobs:
  run-deploy:
    runs-on: ubuntu-latest
    container: jekyll/builder:4.0.0
    steps:
      # Checkout
      - name: Checkout Code
        uses: actions/checkout@master
      # Note the following may not be required in future versions of Jekyll Build Actions
      - name: Make build destination directory
        run: chmod -R 777 /__w/roxberry/roxberry
      # Jekyll  
      - name: Get Jekyll Dependencies
        run: |
          gem install bundler jekyll
          bundle install --jobs 4 --retry 3
      # Grunt
      - name: Get Grunt Dependencies
        run: |
          npm install
      # Build
      - name: Grunt Deploy
        run: 
          npm run build
      # Git
      - name: Git
        run: |
          git config --global user.email "roxberry@outlook.com"
          git config --global user.name "Mark Roxberry"
          git clone https://${{ secrets.GITHUB_TOKEN }}@github.com:roxberry/roxberry.git
          git checkout deployment
          git commit -m "Add changes" -a
          git push -f
        
        
