name: Jekyll Build - Optional Deploy

on:
  push:
    branches:
    - masterx

jobs: 
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Building a jekyll site from configured directory, maybe deploying it.
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          JEKYLL_ROOT: "./"
          REMOTE_BRANCH: "deployment"
        uses: roxberry/jekyll-build-optional-deploy-gh-pages@master
