name: deploy

on:
  push:
    branches:
      - masterx
  pull_request:
    branches:
      - masterx
    paths:
      - 'dist/**'

jobs:
  run-deploy:
    runs-on: ubuntu-latest
    container: jekyll/builder:4.0.0
    steps:
      # Checkout
      - name: Checkout Code
        uses: actions/checkout@master
      # Note the following may not be required in future versions of Jekyll Build Actions
      - name: Make build destination directory
        run: chmod -R 777 /__w/roxberry/roxberry
      # Jekyll  
      - name: Get Jekyll Dependencies
        run: |
          gem install bundler jekyll
          bundle install --jobs 4 --retry 3
      # Grunt
      - name: Get Grunt Dependencies
        run: |
          npm install
      # Build
      - name: Grunt Deploy
        run: 
          npm run build
      # Git
      - name: Git Config
        run: |
          git config --global user.email "roxberry@outlook.com"
          git config --global user.name "Mark Roxberry"
      # Deploy to local repo
      - name: Deploy
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: deployment-test
          FOLDER: dest
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        
