name: deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - deployment
    paths:
      - 'dist/**'

jobs:
  run-deploy:
    runs-on: ubuntu-latest
    container: jekyll/jekyll
    steps:
      # Checkout
      - name: Checkout Code
        uses: actions/checkout@master
      # Jekyll  
      - name: Get Jekyll Dependencies
        run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
      # Grunt
      - name: Get Grunt Dependencies
        run: npm install
      # Build
      - name: Grunt Build and Copy
        run: grunt build && grunt copy
