name: deploy

on:
  push:
    branches:
      - master

jobs:
  run-deploy:
    runs-on: ubuntu-latest
    container: jekyll/jekyll
    steps:
      # Checkout
      - name: checkout
        uses: actions/checkout@master
        
      - name: dependencies
        run: gem install
